# Site settings
title: Stock Indicators for Developers
tagline: Tools for software trading systems
lang: en-US

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stockindicators.dev" # hostname & protocol

# social media information
image:
  path: /assets/social-banner.png
  height: 640
  width: 1280

logo: /assets/icons/android-chrome-512x512.png

organization:
  name: FacioQuo
  email: info@facioquo.com

# Build settings
plugins:
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at

# Theme settings
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/facioquo" }

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "base"
      footer: true
