name: Deploy website

on: workflow_dispatch

concurrency:
  group: ${{ github.ref }}

jobs:
  deploy:
    name: Cloudflare Pages
    runs-on: ubuntu-latest

    env:
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

    environment:
      name: stockindicators.dev
      url: ${{ steps.deploy.outputs.deployment-alias-url }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Define tag
        id: tag
        run: echo "version=$(date +'%Y.%m.%d')-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Replace cache markers
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "YYYY.MM.DD"
          replace: "${{ steps.tag.outputs.version }}"
          regex: false

      - name: Build site (production)
        if: github.ref == 'refs/heads/main'
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build

      - name: Build site (preview)
        if: github.ref != 'refs/heads/main'
        env:
          JEKYLL_ENV: preview
        run: bundle exec jekyll build

      - name: Publish to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@b2a0191ce60d21388e1a8dcc968b4e9966f938e1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "latest"
          command: >
            pages deploy _site
            --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }}
