name: Deploy website

on: [workflow_dispatch]

concurrency:
  group: ${{ github.ref }}

jobs:
  deploy:
    name: Cloudflare Pages
    runs-on: ubuntu-latest

    env:
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

    environment:
      name: stockindicators.dev

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 1 # Increment this number if you need to re-download cached gems

      - name: Define tag
        id: tag
        run: echo "version=$(date +'%Y.%m.%d')-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Replace cache markers
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "YYYY.MM.DD"
          replace: "${{ steps.tag.outputs.version }}"
          regex: false
          
      - name: Build site (production)
        if: github.ref == 'refs/heads/main'
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build

      - name: Build site (preview)
        if: github.ref != 'refs/heads/main'
        env:
          JEKYLL_ENV: preview
        run: bundle exec jekyll build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: _site
          wranglerVersion: 'latest'
