name: Website

on:
  pull_request:
    branches: ["main"]

jobs:
  testing:
    name: test a11y
    runs-on: ubuntu-20.04
    env:
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build

      - name: Serve site
        run: bundle exec jekyll serve --detach

      - name: Show environment
        run: npx pa11y --environment

      - name: Test accessibility
        run: npx pa11y-ci --sitemap http://127.0.0.1:4000/sitemap.xml
